# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    # filters_sets:
    #     carre: #nom  du filtre
    #         quality: 75 #qualité de l'image
    #         filters:
    #             thumbnail:
    #                 size: [200, 200]
    #                 mode: outbund