# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        company_logo:
            uri_prefix: /uploads/logo    
            upload_destination: '%kernel.project_dir%/public/assets/logo%'
